name: github-action-prettier-format
run-name: Formatting With Prettier
on: [pull_request]
jobs:
    github-action-prettier-format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22.17.1"
            - run: npm ci
            - run: npm run prettier
